#include "cube.h"
#include <AL/efx.h>

enum
{
    SOUNDENV_PROP_DENSITY = 0,
    SOUNDENV_PROP_DIFFUSION,
    SOUNDENV_PROP_GAIN,
    SOUNDENV_PROP_GAINHF,
    SOUNDENV_PROP_GAINLF,
    SOUNDENV_PROP_DECAY_TIME,
    SOUNDENV_PROP_DECAY_HFRATIO,
    SOUNDENV_PROP_DECAY_LFRATIO,
    SOUNDENV_PROP_REFL_GAIN,
    SOUNDENV_PROP_REFL_DELAY,
    SOUNDENV_PROP_LATE_GAIN,
    SOUNDENV_PROP_LATE_DELAY,
    SOUNDENV_PROP_ECHO_TIME,
    SOUNDENV_PROP_ECHO_DELAY,
    SOUNDENV_PROP_MOD_TIME,
    SOUNDENV_PROP_MOD_DELAY,
    SOUNDENV_PROP_ABSORBTION_GAINHF,
    SOUNDENV_PROP_HFREFERENCE,
    SOUNDENV_PROP_LFREFERENCE,
    SOUNDENV_PROP_ROOM_ROLLOFF,
    SOUNDENV_PROP_DECAY_HFLIMIT,

    SOUNDENV_PROPS
};

static propertydef soundenvprops[SOUNDENV_PROPS] =
{
    propertydef(
        "density",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_DENSITY, AL_EAXREVERB_DEFAULT_DENSITY, AL_EAXREVERB_MAX_DENSITY
    ),
    propertydef(
        "diffusion",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_DIFFUSION, AL_EAXREVERB_DEFAULT_DIFFUSION, AL_EAXREVERB_MAX_DIFFUSION
    ),
    propertydef(
        "gain",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_GAIN, AL_EAXREVERB_DEFAULT_GAIN, AL_EAXREVERB_MAX_GAIN
    ),
    propertydef(
        "gainhf",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_GAINHF, AL_EAXREVERB_DEFAULT_GAINHF, AL_EAXREVERB_MAX_GAINHF
    ),
    propertydef(
        "gainlf",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_GAINLF, AL_EAXREVERB_DEFAULT_GAINLF, AL_EAXREVERB_MAX_GAINLF
    ),
    propertydef(
        "decay_time",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_DECAY_TIME, AL_EAXREVERB_DEFAULT_DECAY_TIME, AL_EAXREVERB_MAX_DECAY_TIME
    ),
    propertydef(
        "decay_hfratio",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_DECAY_HFRATIO, AL_EAXREVERB_DEFAULT_DECAY_HFRATIO, AL_EAXREVERB_MAX_DECAY_HFRATIO
    ),
    propertydef(
        "decay_lfratio",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_DECAY_LFRATIO, AL_EAXREVERB_DEFAULT_DECAY_LFRATIO, AL_EAXREVERB_MAX_DECAY_LFRATIO
    ),
    propertydef(
        "reflections_gain",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_REFLECTIONS_GAIN, AL_EAXREVERB_DEFAULT_REFLECTIONS_GAIN, AL_EAXREVERB_MAX_REFLECTIONS_GAIN
    ),
    propertydef(
        "reflections_delay",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_REFLECTIONS_DELAY, AL_EAXREVERB_DEFAULT_REFLECTIONS_DELAY, AL_EAXREVERB_MAX_REFLECTIONS_DELAY
    ),
    propertydef(
        "late_gain",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_LATE_REVERB_GAIN, AL_EAXREVERB_DEFAULT_LATE_REVERB_GAIN, AL_EAXREVERB_MAX_LATE_REVERB_GAIN
    ),
    propertydef(
        "late_delay",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_LATE_REVERB_DELAY, AL_EAXREVERB_DEFAULT_LATE_REVERB_DELAY, AL_EAXREVERB_MAX_LATE_REVERB_DELAY
    ),
    propertydef(
        "echo_time",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_ECHO_TIME, AL_EAXREVERB_DEFAULT_ECHO_TIME, AL_EAXREVERB_MAX_ECHO_TIME
    ),
    propertydef(
        "echo_depth",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_ECHO_DEPTH, AL_EAXREVERB_DEFAULT_ECHO_DEPTH, AL_EAXREVERB_MAX_ECHO_DEPTH
    ),
    propertydef(
        "mod_time",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_MODULATION_TIME, AL_EAXREVERB_DEFAULT_MODULATION_TIME, AL_EAXREVERB_MAX_MODULATION_TIME
    ),
    propertydef(
        "mod_depth",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_MODULATION_DEPTH, AL_EAXREVERB_DEFAULT_MODULATION_DEPTH, AL_EAXREVERB_MAX_MODULATION_DEPTH
    ),
    propertydef(
        "air_absorbtion_gainhf",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_AIR_ABSORPTION_GAINHF, AL_EAXREVERB_DEFAULT_AIR_ABSORPTION_GAINHF, AL_EAXREVERB_MAX_AIR_ABSORPTION_GAINHF
    ),
    propertydef(
        "hfref",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_HFREFERENCE, AL_EAXREVERB_DEFAULT_HFREFERENCE, AL_EAXREVERB_MAX_HFREFERENCE
    ),
    propertydef(
        "lfref",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_LFREFERENCE, AL_EAXREVERB_DEFAULT_LFREFERENCE, AL_EAXREVERB_MAX_LFREFERENCE
    ),
    propertydef(
        "room_rolloff_factor",
        PROP_FLOAT,
        AL_EAXREVERB_MIN_ROOM_ROLLOFF_FACTOR, AL_EAXREVERB_DEFAULT_ROOM_ROLLOFF_FACTOR, AL_EAXREVERB_MAX_ROOM_ROLLOFF_FACTOR
    ),
    propertydef(
        "decay_hflimit",
        PROP_INT,
        AL_EAXREVERB_MIN_DECAY_HFLIMIT, AL_EAXREVERB_DEFAULT_DECAY_HFLIMIT, AL_EAXREVERB_MAX_DECAY_HFLIMIT
    )
};
